version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: crm_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5436:5432'

  app:
    build: .
    container_name: crm_app
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "node app.js"

volumes:
  postgres-data:
